<?php
/* @var $block Remarkety\Mgconnector\Block\Frontend\Tracking\General */
?>
<?php if ($block->isWebtrackingActivated()): ?>
    <script>
        var _rmData = _rmData || [];
        _rmData.push(['setStoreKey', '<?php echo $block->getRemarketyPublicId(); ?>']);
        <?php $_rmEmail = $block->getEmail(); if ($_rmEmail): ?>
        _rmData.push(["setCustomer", "<?php echo $_rmEmail; ?>"]);
        <?php endif; ?>
    </script>
    <script>(function(d, t) {
            var g = d.createElement(t),
                s = d.getElementsByTagName(t)[0];
            g.src = 'https://s3.amazonaws.com/downloads.remarkety.com/webtracking/remarkety.js';
            s.parentNode.insertBefore(g, s);
        }(document, 'script'));</script>
<?php endif; ?>