<?php
/* @var $block Remarkety\Mgconnector\Block\Frontend\Tracking\Product */
?>
<?php if ($block->isWebtrackingActivated()): ?>
    <script>
        var _rmData = _rmData || [];
        _rmData.push(['productView', {
            productId: <?= $block->getActiveProduct()->getId(); ?>,
            productCategories: <?= $block->getCategoryNames(); ?>,
            productCategoriesIds: <?= $block->getCategoryIds(); ?>,
        }]);
    </script>
<?php endif; ?>
