<?php if ($block->getAddToCartEventViewModel()->isEnabled()): ?>
    <script>
        require([
            'jquery'
        ], function($) {
            "use strict"

            $(document).on('ajax:addToCart', function (e, data) {
                $.ajax({
                    url: '<?= $block->getAddToCartEventViewModel()->getUrl() ?>',
                    type: 'get',

                    success: function (res) {
                        var _rmData = _rmData || [];
                        _rmData.push(['track', 'carts/update', res]);
                    }
                })
            });
        })
    </script>
<?php endif; ?>
