<?php
$_element = $this->getElement();
$_note    = $_element->getNote();
$_trId    = $_element->getHtmlContainerId();
$_class   = $_element->getFieldsetHtmlClass();
?>
<?php if (!$_element->getNoDisplay()): ?>
<tr<?php if($_trId): ?> id="<?php echo $_trId ?>"<?php endif; ?>>
    <?php if ($_element->getType()=='hidden'): ?>
        <td colspan="2" class="hidden"><?php echo trim($_element->getElementHtml()) ?></td>
    <?php else: ?>
        <?php $label = $_element->getLabel() ? trim($_element->getLabelHtml()) : false ?>
        <?php if(!empty($label)): ?>
                <td class="label<?php echo $_class ? " {$_class}-label" : ''?>"><?php echo $label ?></td>
        <?php endif; ?>
        <td <?php echo empty($label) ? 'colspan="2"' : '' ?>
            class="<?php echo $_element->hasValueClass() ? $_element->getValueClass() : 'value' ?><?php echo $_class ? " {$_class}-value" : ''?>"
            style="padding: 5px 0;">
            <?php echo trim($_element->getElementHtml()) ?>
            <?php if ($_note): ?>
                <p class="note<?php echo $_class ? " {$_class}-note" : ''?>" id="note_<?php echo $_element->getId()?>"><span><?php echo $_note ?></span></p>
            <?php endif ?>
        </td>
    <?php endif; ?>
</tr>
<?php endif; ?>
