<form class="form" action="" method="post">

    <div class="page-main-actions">
        <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
            <div class="page-actions-inner" data-title="bnaya2 test">
                <div class="page-actions-buttons">
                    <button id="save" title="Save Settings" type="submit"
                            class="action- scalable save primary ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"
                            data-form-role="save" data-ui-id="save-button" role="button" aria-disabled="false"><span
                                class="ui-button-text">
                        Save Settings
                        </span></button>
                </div>
            </div>
        </div>
    </div>
    <fieldset class="admin__fieldset">
        <legend class="admin__legend">General</legend>
        <div class="admin__field">
            <label for="pos_id" class="admin__field-label">
                <span><?php echo __('Customer POS ID Attribute') ?></span>
            </label>

            <div class="admin__field-control _with-tooltip">
                <select id="pos_id" name="pos_id" class="admin__control-select">
                    <option value="">- Do not sync POS ID -</option>
                    <?php foreach ($this->getPosIdOptions() as $code => $name): ?>
                        <option
                                value="<?php echo $code; ?>"
                            <?php if ($code == $this->getCurrentPOSCode()) { echo 'selected="selected"'; } ?>
                        ><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <div class="admin__field-tooltip">
                    <span class="admin__field-tooltip-action action-help"></span>
                    <div class="admin__field-tooltip-content">If you are syncing POS transactions to Remarkety from another source, mapping the POS ID from Magento will help us merge the data between the data sources.</div>
                </div>
            </div>
        </div>

        <div class="admin__field">
            <label for="with_fpt" class="admin__field-label">
                <span><?php echo __('Enabled Fixed Product Tax (FPT)') ?></span>
            </label>

            <div class="admin__field-control _with-tooltip">
                <select id="with_fpt" name="with_fpt" class="admin__control-select">
                    <?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
                        <option
                                value="<?php echo $code; ?>"
                            <?php if ($code && $this->getFptEnabled()) { echo 'selected="selected"'; } ?>
                        ><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <div class="admin__field-tooltip">
                    <span class="admin__field-tooltip-action action-help"></span>
                    <div class="admin__field-tooltip-content">Enable this setting if your store uses Fixed Product Tax (FPT)</div>
                </div>
            </div>
        </div>
        <div class="admin__field">
            <label for="with_fpt" class="admin__field-label">
                <span><?php echo __('Customer address field') ?></span>
            </label>

            <div class="admin__field-control _with-tooltip">
                <select id="customer_address" name="customer_address" class="admin__control-select">
                    <option value="billing" <?php if ('billing' == $this->getCustomerAddress()) { echo 'selected="selected"'; } ?>>Billing Address</option>
                    <option value="shipping" <?php if ('shipping' == $this->getCustomerAddress()) { echo 'selected="selected"'; } ?>>Shipping Address</option>
                </select>
                <div class="admin__field-tooltip">
                    <span class="admin__field-tooltip-action action-help"></span>
                    <div class="admin__field-tooltip-content">Which default customer address should be sent to Remarkety (default: Billing address).</div>
                </div>
            </div>
        </div>
        <?php if ($this->isIsAwPointsPluginExists()): ?>
            <div class="admin__field">
                <label for="aw_rewards_integrate" class="admin__field-label">
                    <span><?php echo __('Enabled integration with Aheadworks Reward Points') ?></span>
                </label>

                <div class="admin__field-control _with-tooltip">
                    <select id="aw_rewards_integrate" name="aw_rewards_integrate" class="admin__control-select">
                        <?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
                            <option
                                    value="<?php echo $code; ?>"
                                <?php if ($code && $this->isAWRewradPointsEnabled()) { echo 'selected="selected"'; } ?>
                            ><?php echo $name; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>
        <div class="admin__field">
            <label for="pos_id" class="admin__field-label">
                <span><?php echo __('Cart Auto Coupon') ?></span>
            </label>

            <div class="admin__field-control _with-tooltip">
                <select id="cart_auto_coupon" name="cart_auto_coupon" class="admin__control-select">
                    <?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
                        <option
                            value="<?php echo $code; ?>"
                            <?php if ($code && $this->getCartAutoCouponEnabled()) { echo 'selected="selected"'; } ?>
                        ><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <div class="admin__field-tooltip">
                    <span class="admin__field-tooltip-action action-help"></span>
                    <div class="admin__field-tooltip-content">Apply coupon when a “coupon” parameter exists on the cart checkout link</div>
                </div>
            </div>
        </div>
    </fieldset>


    <fieldset class="admin__fieldset">
        <legend class="admin__legend">Website tracking events</legend>
        <div class="admin__field">
            <label for="pos_id" class="admin__field-label">
                <span><?php echo __('Category View') ?></span>
            </label>

            <div class="admin__field-control _with-tooltip">
                <select id="category_view" name="category_view" class="admin__control-select">
                    <?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
                        <option
                                value="<?php echo $code; ?>"
                            <?php if ($code && $this->getEventCategoryView()) { echo 'selected="selected"'; } ?>
                        ><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <div class="admin__field-tooltip">
                    <span class="admin__field-tooltip-action action-help"></span>
                    <div class="admin__field-tooltip-content">Send a "Category View" client-side event when customers view a category page.</div>
                </div>
            </div>
        </div>
        <div class="admin__field">
            <label for="pos_id" class="admin__field-label">
                <span><?php echo __('Search View') ?></span>
            </label>

            <div class="admin__field-control _with-tooltip">
                <select id="search_view" name="search_view" class="admin__control-select">
                    <?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
                        <option
                                value="<?php echo $code; ?>"
                            <?php if ($code && $this->getEventSearchView()) { echo 'selected="selected"'; } ?>
                        ><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <div class="admin__field-tooltip">
                    <span class="admin__field-tooltip-action action-help"></span>
                    <div class="admin__field-tooltip-content">Send a "Search View" client-side event when customers search for a product.</div>
                </div>
            </div>
        </div>
        <div class="admin__field">
            <label for="pos_id" class="admin__field-label">
                <span><?php echo __('Cart Updated') ?></span>
            </label>

            <div class="admin__field-control _with-tooltip">
                <select id="cart_updated" name="cart_updated" class="admin__control-select">
                    <?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
                        <option
                                value="<?php echo $code; ?>"
                            <?php if ($code && $this->getEventCartView()) { echo 'selected="selected"'; } ?>
                        ><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <div class="admin__field-tooltip">
                    <span class="admin__field-tooltip-action action-help"></span>
                    <div class="admin__field-tooltip-content">Send a "Cart Updated" client-side event when customers update their cart.</div>
                </div>
            </div>
        </div>
    </fieldset>

	<fieldset class="admin__fieldset">
		<legend class="admin__legend">Popup</legend>
		<div class="admin__field">
			<label for="popup_enabled" class="admin__field-label">
				<span><?php echo __('Popup Enabled') ?></span>
			</label>

			<div class="admin__field-control _with-tooltip">
				<select id="popup_enabled" name="popup_enabled" class="admin__control-select">
            <?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
						<option
							value="<?php echo $code; ?>"
                  <?php if ($code && $this->getPopupEnabled()) { echo 'selected="selected"'; } ?>
						><?php echo $name; ?></option>
            <?php endforeach; ?>
				</select>
			</div>
		</div>
	</fieldset>
	<fieldset class="admin__fieldset">
		<legend class="admin__legend">Products</legend>
		<div class="admin__field">
			<label for="is_not_visible_product_enabled" class="admin__field-label">
				<span><?php echo __('Consider "Not Visible Individually" as Enabled') ?></span>
			</label>

			<div class="admin__field-control _with-tooltip">
				<select id="is_not_visible_product_enabled" name="is_not_visible_product_enabled" class="admin__control-select">
            <?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
						<option
							value="<?php echo $code; ?>"
                  <?php if ($code && $this->isNotVisibleProductEnabled()) { echo 'selected="selected"'; } ?>
						><?php echo $name; ?></option>
            <?php endforeach; ?>
				</select>
				<div class="admin__field-tooltip">
					<span class="admin__field-tooltip-action action-help"></span>
					<div class="admin__field-tooltip-content">When a product is Enabled but set to Not Visible Individually in Magento, it will be marked as Enabled in Remarkety if this checkbox is checked and Disabled otherwise.</div>
				</div>
			</div>
		</div>
		<div class="admin__field">
			<label for="customer_group_for_price_rules" class="admin__field-label">
				<span><?php echo __('Default product price customer groups') ?></span>
			</label>

			<div class="admin__field-control _with-tooltip">
				<select id="customer_group_for_price_rules" name="customer_group_for_price_rules" class="admin__control-select">
            <?php foreach ($this->getCustomerGroups() as $id => $name): ?>
						<option
							value="<?php echo $id; ?>"
                  <?php if ((string)$id === (string)$this->getCustomerGroupForPriceRules()) { echo 'selected="selected"'; } ?>
						><?php echo $name; ?></option>
            <?php endforeach; ?>
				</select>
				<div class="admin__field-tooltip">
					<span class="admin__field-tooltip-action action-help"></span>
					<div class="admin__field-tooltip-content">...........</div>
				</div>
			</div>
		</div>
	</fieldset>
		<fieldset class="admin__fieldset">
			<legend class="admin__legend">Email Consent on Checkout Page</legend>
			<div class="admin__field">
				<label for="" class="admin__field-label">
					<span><?php echo __('Collect Email consent in checkout page') ?></span>
				</label>

				<div class="admin__field-control _with-tooltip">
					<select id="email_consent" name="email_consent" class="admin__control-select">
							<?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
								<option
									value="<?php echo $code; ?>"
										<?php if ($code && $this->getEmailConsentEnabled()) { echo 'selected="selected"'; } ?>
									><?php echo $name; ?></option>
							<?php endforeach; ?>
					</select>
					<div class="admin__field-tooltip">
						<span class="admin__field-tooltip-action action-help"></span>
						<div class="admin__field-tooltip-content">Enabling the "Collect email consent on checkout page"
							will insert a checkbox on the checkout page, allowing customers to opt into marketing
							communications via text messages.</div>
					</div>
				</div>
			</div>
			<div class="admin__field">
				<label for="" class="admin__field-label">
					<span><?php echo __('Email consent checkbox position') ?></span>
				</label>

				<div class="admin__field-control _with-tooltip">
					<select id="email_consent_checkbox_position" name="email_consent_checkbox_position" class="admin__control-select">
							<?php foreach ($this->getFormFieldPositions() as $code => $name): ?>
								<option
									value="<?php echo $name; ?>"
									<?php if ($name == $this->getEmailConsentCheckboxPosition()) { echo 'selected="selected"'; } ?>
									><?php echo $name; ?></option>
							<?php endforeach; ?>
					</select>
					<div class="admin__field-tooltip">
						<span class="admin__field-tooltip-action action-help"></span>
						<div class="admin__field-tooltip-content">The placement of the consent checkbox within the checkout form,
							a lower number indicates that the checkbox will be positioned at the top of the form.</div>
					</div>
				</div>
			</div>
			<div class="admin__field">
				<label for="" class="admin__field-label">
					<span><?php echo __('Email consent checkbox label') ?></span>
				</label>

				<div class="admin__field-control _with-tooltip">
					<input type="text" id="email_consent_checkbox_lable_value" name="email_consent_checkbox_lable_value"
							 class="admin__control-text"
							 value="<?php echo !empty($this->getEmailConsentCheckboxLabelValue()) ? $this->getEmailConsentCheckboxLabelValue() : 'Subscribe to receiving exclusive discounts via email ';?>">
					<div class="admin__field-tooltip">
						<span class="admin__field-tooltip-action action-help"></span>
						<div class="admin__field-tooltip-content">Consent label value</div>
					</div>
				</div>
			</div>
		</fieldset>

		<fieldset class="admin__fieldset">
			<legend class="admin__legend">SMS Consent on Checkout Page</legend>
			<div class="admin__field">
				<label for="" class="admin__field-label">
					<span><?php echo __('Collect SMS consent in checkout page') ?></span>
				</label>

				<div class="admin__field-control _with-tooltip">
					<select id="sms_consent" name="sms_consent" class="admin__control-select">
							<?php foreach ($this->getEnabledDisabledOptions() as $code => $name): ?>
								<option
									value="<?php echo $code; ?>"
										<?php if ($code && $this->getSmsConsentEnabled()) { echo 'selected="selected"'; } ?>
									><?php echo $name; ?></option>
							<?php endforeach; ?>
					</select>
					<div class="admin__field-tooltip">
						<span class="admin__field-tooltip-action action-help"></span>
						<div class="admin__field-tooltip-content">Enabling the "Collect sms consent on checkout page"
							will insert a checkbox on the checkout page, allowing customers to opt into marketing
							communications via text messages.</div>
					</div>
				</div>
			</div>
			<div class="admin__field">
				<label for="" class="admin__field-label">
					<span><?php echo __('SMS consent checkbox position') ?></span>
				</label>

				<div class="admin__field-control _with-tooltip">
					<select id="sms_consent_checkbox_position" name="sms_consent_checkbox_position" class="admin__control-select">
							<?php foreach ($this->getFormFieldPositions() as $code => $name): ?>
								<option
									value="<?php echo $name; ?>"
									<?php if ($name == $this->getSMSConsentCheckboxPosition()) { echo 'selected="selected"'; } ?>
									><?php echo $name; ?></option>
							<?php endforeach; ?>
					</select>
					<div class="admin__field-tooltip">
						<span class="admin__field-tooltip-action action-help"></span>
						<div class="admin__field-tooltip-content">The placement of the consent checkbox within the checkout form,
							a lower number indicates that the checkbox will be positioned at the top of the form.</div>
					</div>
				</div>
			</div>
			<div class="admin__field">
				<label for="" class="admin__field-label">
					<span><?php echo __('SMS consent checkbox label') ?></span>
				</label>

				<div class="admin__field-control _with-tooltip">
					<input type="text" id="sms_consent_checkbox_lable_value" name="sms_consent_checkbox_lable_value"
							 class="admin__control-text"
							 value="<?php echo !empty($this->getSMSConsentCheckboxLabelValue()) ? $this->getSMSConsentCheckboxLabelValue() :  'Subscribe to receiving exclusive discounts via sms ';?>">
					<div class="admin__field-tooltip">
						<span class="admin__field-tooltip-action action-help"></span>
						<div class="admin__field-tooltip-content">Consent label value</div>
					</div>
				</div>
			</div>
		</fieldset>

    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
</form>
